contribute_button_color:
  default: yellow
  type: enum
  description: "Set color based on level of reserves as determined by the tiaa-forum.org Treasurer."
  choices:
    - red
    - yellow
    - green
    - blue

contribute_text_color:
  default: white
  type: enum
  description: "Set color of text for button (should probably be white for any button color but yellow)."
  choices:
    - white
    - black

display_contribute_banner:
  type: bool
  default: true
  description: "Select to enable the Contribute Banner to the brand header."
